### ISSUE TITLE
Help me please :(

### ISSUE THREAD

**Issue by SoyJuandaFox777** [g3th/Selenium_Account_Checkers#2]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Selenium_Account_Checkers/hbo.py", line 20, in <module>
    with open(file_directory, 'r') as hbo:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/data/data/com.termux/files/home/Selenium_Account_Checkers/hbo'

**Comment by g3th** [comment]
Hi there,

[HBO Only Script]

This error occurs because you don't have a combo-list named 'hbo' in the appropriate folder.

I have added error-checking which informs you that the file is missing in the directory where the program resides.

I have also fixed an issue with Shadow DOMs, which hid email and password input boxes, so everything is working again.
