### ISSUE TITLE
ComboList Error

### ISSUE THREAD

**Issue by zak799** [g3th/Selenium_Account_Checkers#3]
When Running The Code, And Adding A ComboList Named 'disney'. I am still getting this error:

```
No combo-list found in directory:
# Removing Directory Name For Time Being /:

Add one, and name it 'disney' before starting the program.
```
![Scren](https://github.com/g3th/Selenium_Account_Checkers/assets/129955960/3e8e4990-b1d1-4f5f-9633-8fde7f46cc6e)

**Comment by g3th** [comment]
Hi,

Which operating system are you using?

**Comment by zak799** [comment]
I am using Windows 10

**Comment by zak799** [comment]
> Hi,
> 
> Which operating system are you using?

What is it built for?

**Comment by g3th** [comment]
The program works fine in Powershell (or Git Bash/Bash in Windows). Although in Powershell you won't get the correct TUI Ascii graphics and colours due to differences in Operating Systems.

You might find this video helpful:


https://github.com/g3th/Selenium_Account_Checkers/assets/74467654/ab609548-2e0d-45bc-b055-850d757cf18e

You can install git for Windows (for bash) or other bash terminal, then install python through scoop, then install the necessary chromedriver and dependencies, and everything should run fine. Let me know if you still have problems, or if something isn't working correctly, but it will likely be user error.

**Comment by smokiejoe611** [comment]
Hello g3th, I had the same problem as SirScripter. I'm also running Windows 10. I installed everything accordingly as per your video with all the needed modules for Git bash and Powershell. All was succesfull, however i still get the error "No combo-list found in directory." I know it's probably user error like you say but i'm stuck lol. Thank you for sharing your hard work and knowledge of these checkers you made. I'm learning a lot and hope to someday make my own checkers.

![Capture2](https://github.com/g3th/Selenium_Account_Checkers/assets/106884644/78ca672c-e870-451e-bd2d-72197b115a76)

         
![Capture1](https://github.com/g3th/Selenium_Account_Checkers/assets/106884644/b82ff456-a9da-4d2f-b2a8-5d545692911a)

**Comment by smokiejoe611** [comment]
Ok, it was the old nut behind the wheel.... no combo list was found because i did not load it properly in the folder. Too many beers today.

![Capture2](https://github.com/g3th/Selenium_Account_Checkers/assets/106884644/86aa0e56-3d13-431f-b784-4916f990e47b)


![Capture1](https://github.com/g3th/Selenium_Account_Checkers/assets/106884644/4c69f774-76db-4109-bb5c-c01f69ee6fc0)

Thanks again bro, i'll check out the rest of the package tomorrow. 
![snooze](https://github.com/g3th/Selenium_Account_Checkers/assets/106884644/a4ccbf8d-f71e-41d3-a89c-c03eb3f333a3)

**Comment by g3th** [comment]
> Ok, it was the old nut behind the wheel.... no combo list was found because i did not load it properly in the folder. Too many beers today.

Glad you got it working. I would not recommend checking such a large list, however, as it will be quite slow. I don't run 'grid' or 'threading' yet, but even that will not drastically increase speeds.

Essentially, it is just to watch free TV. If you have different needs, I would recommend the OpenBullet suite instead, but that would require an entirely different setup.

I will close the issue, but you are still free to ask your questions here.

**Comment by smokiejoe611** [comment]
Yeah, I figured my combo was going to be too large. I did make a shorter, more targeted combo list of paramount accounts and it works great. I was more interested in how your checkers work than getting Tv for now.  OpenBullet makes it pretty easy and fast to get IPTV for me. There is one particular IPTV site that I would love to make a Standalone exe. app so I could send to my friends that do not understand how OpenBullet works. I figured it would be nice to make a one click app so it scans the site with a known good combo list that I always use that gets hits. I don't know anything about "grid" or "threading" but it sounds like it improves CPM. Anyway, I have a lot of learning to do and appreciate you sharing your apps and knowledge. Oh and thanks for the tutorial on getting my powershell and git bash going with python. Unfortunately, I had to do a system restore yesterday and i have to do it all over again.
